import { useEffect, useMemo, useState } from 'react'
import { api, clearSession, getSession, mediaUrl, setSession } from './api'

const today = new Date().toISOString().slice(0, 10)
const emptyEvent = () => ({ event_id: crypto.randomUUID(), activity: '', start_time: '09:00', end_time: '11:00', weather: { status: 'Mild and dry', temperature_c: 20, precipitation: 'none' } })

function App() {
  const [session, setSessionState] = useState(getSession())
  const [page, setPage] = useState('today')
  const [items, setItems] = useState([])
  const [user, setUser] = useState(session?.user || null)
  const [error, setError] = useState('')

  const authenticate = (next) => { setSession(next); setSessionState(next); setUser(next.user); setPage('today') }
  const signOut = () => { clearSession(); setSessionState(null); setUser(null); setItems([]) }
  const refreshItems = async (params) => { try { setItems(await api.items(params)) } catch (e) { setError(e.message) } }
  useEffect(() => { if (session) { api.me().then(setUser).catch(() => signOut()); refreshItems() } }, [session])

  if (!session) return <Auth onAuthenticate={authenticate} />
  return <div className="shell">
    <header className="topbar"><button className="wordmark" onClick={() => setPage('today')}>WEAR THIS</button><div className="topbar-right"><span className="desktop-only">Your closet, thoughtfully styled.</span><button className="avatar" onClick={() => setPage('profile')}>{(user?.first_name || user?.email || 'W')[0].toUpperCase()}</button></div></header>
    {error && <div className="notice error">{error}<button onClick={() => setError('')}>×</button></div>}
    <main>
      {page === 'today' && <Today items={items} onPlan={() => setPage('plan')} />}
      {page === 'wardrobe' && <Wardrobe items={items} refresh={refreshItems} setError={setError} />}
      {page === 'plan' && <Planner items={items} setError={setError} />}
      {page === 'profile' && <Profile user={user} setUser={setUser} signOut={signOut} setError={setError} />}
    </main>
    <nav className="nav">{[['today','⌂','Today'],['wardrobe','⌑','Wardrobe'],['plan','◫','Plan'],['profile','◯','Profile']].map(([id,icon,label]) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}><b>{icon}</b><span>{label}</span></button>)}</nav>
  </div>
}

function Auth({ onAuthenticate }) {
  const [mode, setMode] = useState('login'); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const [form, setForm] = useState({ email: '', password: '', first_name: '', last_name: '' })
  const change = (key) => (e) => setForm({ ...form, [key]: e.target.value })
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const data = mode === 'login' ? await api.login({ email: form.email, password: form.password }) : await api.register({ ...form, password_confirm: form.password }); onAuthenticate(data) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <div className="auth-page"><section className="auth-art"><div className="auth-brand">WEAR THIS</div><p>PERSONAL STYLE,<br />SIMPLIFIED.</p><div className="art-card"><span>✦</span><i>Build outfits from<br />what you already own.</i></div></section><section className="auth-panel"><div className="auth-form"><div className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'A NEW CHAPTER'}</div><h1>{mode === 'login' ? <>Dress for<br />your day.</> : <>Meet your<br />better closet.</>}</h1><p className="muted">{mode === 'login' ? 'Your wardrobe, fresh possibilities.' : 'Start saving pieces and planning with intention.'}</p><form onSubmit={submit}>{mode === 'register' && <div className="two-col"><label>First name<input value={form.first_name} onChange={change('first_name')} /></label><label>Last name<input value={form.last_name} onChange={change('last_name')} /></label></div>}<label>Email<input type="email" required value={form.email} onChange={change('email')} placeholder="you@example.com" /></label><label>Password<input type="password" required minLength="8" value={form.password} onChange={change('password')} placeholder="At least 8 characters" /></label>{error && <p className="form-error">{error}</p>}<button className="primary full" disabled={busy}>{busy ? 'Just a moment…' : mode === 'login' ? 'Sign in →' : 'Create account →'}</button></form><p className="switch">{mode === 'login' ? 'New to Wear This?' : 'Already have an account?'} <button onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></div></section></div>
}

function Today({ items, onPlan }) { return <section className="page today"><div className="eyebrow">{new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date())}</div><h1>Dress for<br />the day ahead.</h1><div className="hero"><div><span className="weather">☀  20°C · Mild & dry</span><p>One wardrobe.<br />So many directions.</p><button className="primary" onClick={onPlan}>Plan my day <span>→</span></button></div><div className="hero-shapes"><div className="shirt">⌇</div><div className="circle"></div><div className="shoe">⌁</div></div></div><div className="section-row"><div><div className="eyebrow">TODAY'S FLOW</div><h2>{items.length ? 'Ready when you are.' : 'A little space for possibility.'}</h2></div><button className="text-button" onClick={onPlan}>Build a plan →</button></div><div className="empty-card"><span>{items.length ? '✦' : '♢'}</span><div><strong>{items.length ? `${items.length} pieces waiting to be styled` : 'Your wardrobe is empty'}</strong><p>{items.length ? 'Add events, then we’ll build an outfit around the day.' : 'Add a few clothes so we can create outfit ideas from things you actually own.'}</p></div></div></section> }

function Wardrobe({ items, refresh, setError }) {
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('all'); const [uploading, setUploading] = useState(false); const [selected, setSelected] = useState(null)
  useEffect(() => { const timer = setTimeout(() => refresh({ category, search }), 250); return () => clearTimeout(timer) }, [search, category])
  const upload = async (e) => { const image = e.target.files?.[0]; if (!image) return; setUploading(true); try { await api.describe(image); await refresh({ category, search }) } catch (err) { setError(err.message) } finally { setUploading(false); e.target.value = '' } }
  const remove = async (item) => { if (!confirm('Remove this item from your wardrobe?')) return; try { await api.deleteItem(item.id); setSelected(null); refresh({ category, search }) } catch (err) { setError(err.message) } }
  return <section className="page wardrobe"><div className="eyebrow">COLLECTED BY YOU</div><div className="title-row"><h1>Your wardrobe.</h1><label className="primary upload">{uploading ? 'Analyzing…' : '+ Add clothing'}<input type="file" accept="image/*" onChange={upload} disabled={uploading} /></label></div><p className="muted">{items.length} pieces, ready for whatever is next.</p><div className="controls"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by type, color, material…" /> <div className="chips">{[['all','All'],['tops','Tops'],['bottoms','Bottoms'],['outerwear','Outerwear'],['shoes','Shoes'],['other','Other']].map(([key,label]) => <button onClick={() => setCategory(key)} className={key === category ? 'selected' : ''} key={key}>{label}</button>)}</div></div>{items.length === 0 ? <div className="wardrobe-empty"><div>♢</div><h2>{search || category !== 'all' ? 'Nothing found.' : 'Start with a favorite.'}</h2><p>Upload a photo of one piece you own. AI will recognize the details and add it to your closet.</p></div> : <div className="grid">{items.map(item => <button className="clothing-card" onClick={() => setSelected(item)} key={item.id}><img src={mediaUrl(item.image_url)} alt={`${item.primary_color || ''} ${item.type?.subcategory || 'clothing'}`} /><span>{item.primary_color || '—'}</span><strong>{item.type?.subcategory || item.type?.name || 'Clothing item'}</strong></button>)}</div>}{selected && <ItemModal item={selected} onClose={() => setSelected(null)} onDelete={remove} />}</section>
}

function ItemModal({ item, onClose, onDelete }) { const [detail, setDetail] = useState(null); useEffect(() => { api.item(item.id).then(setDetail).catch(() => {}) }, [item.id]); const data = detail || item; const attrs = detail ? [['Colors',detail.colors?.map(x=>x.name).join(', ')],['Materials',detail.materials?.map(x=>x.name).join(', ')],['Styles',detail.styles?.map(x=>x.name).join(', ')],['Details',detail.details?.join(', ')]] : []; return <div className="modal-backdrop" onMouseDown={onClose}><article className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><img src={mediaUrl(data.image_url)} alt="Clothing item" /><div className="modal-content"><div className="eyebrow">WARDROBE ITEM</div><h2>{data.type?.subcategory || data.type?.name || 'Clothing item'}</h2>{attrs.map(([label,value]) => value && <p key={label}><b>{label}</b><br />{value}</p>)}<button className="danger" onClick={() => onDelete(item)}>Delete item</button></div></article></div> }

function Planner({ items, setError }) {
  const [date, setDate] = useState(today); const [events, setEvents] = useState([emptyEvent()]); const [busy, setBusy] = useState(false); const [plan, setPlan] = useState(null)
  const update = (id, field, value) => setEvents(events.map(event => event.event_id === id ? { ...event, [field]: value } : event))
  const weather = (id, field, value) => setEvents(events.map(event => event.event_id === id ? { ...event, weather: { ...event.weather, [field]: field === 'temperature_c' ? Number(value) : value } } : event))
  const generate = async () => { if (!items.length) return setError('Add clothing to your wardrobe before requesting recommendations.'); if (events.some(e => !e.activity.trim())) return setError('Give each event an activity before generating.'); setBusy(true); setPlan(null); try { setPlan(await api.recommend(events)) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <section className="page planner"><div className="eyebrow">MAKE A PLAN</div><h1>What does your day<br />look like?</h1><div className="plan-date"><label>Date<input type="date" value={date} min={today} onChange={e=>setDate(e.target.value)} /></label><span>Weather is included with each moment so your outfit can adapt.</span></div><div className="timeline">{events.map((event,index) => <article className="event" key={event.event_id}><span className="dot">{index + 1}</span><button className="delete-event" onClick={() => setEvents(events.filter(e=>e.event_id!==event.event_id))} disabled={events.length===1}>×</button><label>Activity<input value={event.activity} onChange={e=>update(event.event_id,'activity',e.target.value)} placeholder="e.g. Class on campus" /></label><div className="two-col"><label>Start<input type="time" value={event.start_time} onChange={e=>update(event.event_id,'start_time',e.target.value)} /></label><label>End<input type="time" value={event.end_time} onChange={e=>update(event.event_id,'end_time',e.target.value)} /></label></div><div className="weather-fields"><span>☀</span><label>Conditions<input value={event.weather.status} onChange={e=>weather(event.event_id,'status',e.target.value)} /></label><label>°C<input type="number" value={event.weather.temperature_c} onChange={e=>weather(event.event_id,'temperature_c',e.target.value)} /></label></div></article>)}</div><div className="plan-actions"><button className="secondary" onClick={() => setEvents([...events,emptyEvent()])}>+ Add event</button><button className="primary" onClick={generate} disabled={busy}>{busy ? 'Building your outfit…' : 'Generate outfit →'}</button></div>{plan && <Recommendation plan={plan} items={items} date={date} regenerate={generate} busy={busy} />}</section>
}

function Recommendation({ plan, items, date, regenerate, busy }) { const lookup = useMemo(() => Object.fromEntries(items.map(x=>[x.id,x])), [items]); return <section className="recommendation"><div className="eyebrow">YOUR OUTFIT · {new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</div><h2>Made for your whole day.</h2>{plan.recommendations.map((rec,index) => <article className="recommendation-card" key={rec.event_id}><div className="rec-time">{rec.start_time} — {rec.end_time}</div><h3>{rec.activity}</h3><p>{rec.reason}</p><div className="outfit-items">{rec.clothing_item_ids.map(id => lookup[id] && <div key={id}>{lookup[id].image_url && <img src={mediaUrl(lookup[id].image_url)} alt="" />}<span>{lookup[id].type?.subcategory || 'Piece'}</span></div>)}</div>{(rec.remove_item_ids.length > 0 || rec.put_on_item_ids.length > 0) && <p className="change">{rec.remove_item_ids.length ? `Remove ${rec.remove_item_ids.length} piece${rec.remove_item_ids.length > 1 ? 's' : ''}. ` : ''}{rec.put_on_item_ids.length ? `Add ${rec.put_on_item_ids.length} piece${rec.put_on_item_ids.length > 1 ? 's' : ''}.` : ''}</p>}{rec.warnings.map(w => <p className="warning" key={w}>✦ {w}</p>)}</article>)}<button className="secondary full" onClick={regenerate} disabled={busy}>Regenerate outfit</button></section> }

function Profile({ user, setUser, signOut, setError }) { const [first_name,setFirst] = useState(user?.first_name || ''); const [last_name,setLast] = useState(user?.last_name || ''); const [saving,setSaving] = useState(false); const save = async (e) => { e.preventDefault(); setSaving(true); try { const next = await api.updateMe({first_name,last_name}); setUser(next) } catch (e) { setError(e.message) } finally { setSaving(false) } }; return <section className="page profile"><div className="eyebrow">YOUR ACCOUNT</div><h1>Profile.</h1><div className="profile-card"><div className="large-avatar">{(user?.first_name || user?.email || 'W')[0].toUpperCase()}</div><div><h2>{[user?.first_name,user?.last_name].filter(Boolean).join(' ') || 'Your account'}</h2><p>{user?.email}</p></div></div><form className="settings" onSubmit={save}><h2>Account details</h2><div className="two-col"><label>First name<input value={first_name} onChange={e=>setFirst(e.target.value)} /></label><label>Last name<input value={last_name} onChange={e=>setLast(e.target.value)} /></label></div><button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Save changes'}</button></form><div className="settings"><h2>Preferences</h2><div className="pref"><span>Temperature units</span><b>Celsius</b></div><div className="pref"><span>Notifications</span><b>Coming soon</b></div></div><button className="signout" onClick={signOut}>Sign out</button></section> }

export default App
