# Generated by Django 5.2.17 on 2026-09-14 23:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rise', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('mid', 'Mid'), ('high', 'High'), ('ultra_high', 'Ultra High')], max_length=32)),
                ('leg_shape', models.CharField(choices=[('none', 'None'), ('skinny', 'Skinny'), ('slim', 'Slim'), ('straight', 'Straight'), ('tapered', 'Tapered'), ('wide', 'Wide'), ('flare', 'Flare'), ('bootcut', 'Bootcut'), ('baggy', 'Baggy'), ('carrot', 'Carrot')], max_length=32)),
                ('waistband_type', models.CharField(choices=[('none', 'None'), ('standard', 'Standard'), ('elastic', 'Elastic'), ('drawstring', 'Drawstring'), ('belted', 'Belted'), ('ribbed', 'Ribbed'), ('foldover', 'Foldover')], max_length=32)),
                ('hem_style', models.CharField(choices=[('none', 'None'), ('straight', 'Straight'), ('curved', 'Curved'), ('rounded', 'Rounded'), ('asymmetric', 'Asymmetric'), ('cropped', 'Cropped'), ('ribbed', 'Ribbed'), ('raw', 'Raw'), ('split', 'Split')], max_length=32)),
                ('closure_type', models.CharField(choices=[('none', 'None'), ('zip_fly', 'Zip Fly'), ('button_fly', 'Button Fly'), ('buttons', 'Buttons'), ('drawstring', 'Drawstring'), ('elastic', 'Elastic'), ('hook_and_bar', 'Hook and Bar'), ('side_zip', 'Side Zip')], max_length=32)),
                ('fit', models.CharField(choices=[('skinny', 'Skinny'), ('slim', 'Slim'), ('regular', 'Regular'), ('relaxed', 'Relaxed'), ('loose', 'Loose'), ('baggy', 'Baggy'), ('oversized', 'Oversized')], max_length=32)),
                ('length', models.CharField(choices=[('micro', 'Micro'), ('short', 'Short'), ('knee', 'Knee'), ('below_knee', 'Below Knee'), ('cropped', 'Cropped'), ('ankle', 'Ankle'), ('full', 'Full'), ('floor', 'Floor')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'bottom attributes',
            },
        ),
        migrations.CreateModel(
            name='ClothingAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=128)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('raw_response', models.JSONField(default=dict)),
                ('overall_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'clothing analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingColorGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'clothing color group',
                'verbose_name_plural': 'clothing color groups',
            },
        ),
        migrations.CreateModel(
            name='ClothingDetailGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'clothing detail group',
                'verbose_name_plural': 'clothing detail groups',
            },
        ),
        migrations.CreateModel(
            name='ClothingMaterialGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'clothing material group',
                'verbose_name_plural': 'clothing material groups',
            },
        ),
        migrations.CreateModel(
            name='ClothingPatternGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'clothing pattern group',
                'verbose_name_plural': 'clothing pattern groups',
            },
        ),
        migrations.CreateModel(
            name='ClothingPocketGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'clothing pocket group',
                'verbose_name_plural': 'clothing pocket groups',
            },
        ),
        migrations.CreateModel(
            name='ClothingStyleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'clothing style group',
                'verbose_name_plural': 'clothing style groups',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('charcoal', 'Charcoal'), ('silver', 'Silver'), ('cream', 'Cream'), ('ivory', 'Ivory'), ('beige', 'Beige'), ('tan', 'Tan'), ('khaki', 'Khaki'), ('camel', 'Camel'), ('brown', 'Brown'), ('red', 'Red'), ('burgundy', 'Burgundy'), ('maroon', 'Maroon'), ('pink', 'Pink'), ('rose', 'Rose'), ('orange', 'Orange'), ('coral', 'Coral'), ('peach', 'Peach'), ('yellow', 'Yellow'), ('gold', 'Gold'), ('mustard', 'Mustard'), ('green', 'Green'), ('lime', 'Lime'), ('olive', 'Olive'), ('sage', 'Sage'), ('mint', 'Mint'), ('emerald', 'Emerald'), ('forest_green', 'Forest Green'), ('blue', 'Blue'), ('navy', 'Navy'), ('royal_blue', 'Royal Blue'), ('sky_blue', 'Sky Blue'), ('baby_blue', 'Baby Blue'), ('teal', 'Teal'), ('turquoise', 'Turquoise'), ('purple', 'Purple'), ('lavender', 'Lavender'), ('violet', 'Violet'), ('plum', 'Plum'), ('multicolor', 'Multicolor'), ('transparent', 'Transparent'), ('unknown', 'Unknown')], max_length=32, unique=True)),
                ('hex_value', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('embroidery', 'Embroidery'), ('sequins', 'Sequins'), ('beading', 'Beading'), ('rhinestones', 'Rhinestones'), ('studs', 'Studs'), ('fringe', 'Fringe'), ('tassels', 'Tassels'), ('ruffles', 'Ruffles'), ('bows', 'Bows'), ('lace', 'Lace'), ('patches', 'Patches'), ('applique', 'Applique'), ('distressing', 'Distressing'), ('rips', 'Rips'), ('cutouts', 'Cutouts'), ('pleats', 'Pleats'), ('gathers', 'Gathers'), ('smocking', 'Smocking'), ('quilting', 'Quilting'), ('contrast_stitching', 'Contrast Stitching'), ('piping', 'Piping'), ('chains', 'Chains'), ('buckles', 'Buckles'), ('visible_buttons', 'Visible Buttons'), ('visible_zippers', 'Visible Zippers'), ('logo', 'Logo'), ('graphic', 'Graphic'), ('text', 'Text')], max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'details',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DressAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleeve_length', models.CharField(choices=[('none', 'None'), ('sleeveless', 'Sleeveless'), ('cap', 'Cap'), ('short', 'Short'), ('elbow', 'Elbow'), ('three_quarter', 'Three Quarter'), ('long', 'Long'), ('extra_long', 'Extra Long')], max_length=32)),
                ('sleeve_type', models.CharField(choices=[('none', 'None'), ('regular', 'Regular'), ('raglan', 'Raglan'), ('set_in', 'Set In'), ('drop_shoulder', 'Drop Shoulder'), ('puff', 'Puff'), ('bell', 'Bell'), ('bishop', 'Bishop'), ('batwing', 'Batwing'), ('flutter', 'Flutter'), ('rolled', 'Rolled')], max_length=32)),
                ('neckline', models.CharField(choices=[('none', 'None'), ('crew', 'Crew'), ('round', 'Round'), ('v_neck', 'V-Neck'), ('deep_v', 'Deep V'), ('square', 'Square'), ('scoop', 'Scoop'), ('boat', 'Boat'), ('halter', 'Halter'), ('sweetheart', 'Sweetheart'), ('turtleneck', 'Turtleneck'), ('mock_neck', 'Mock Neck'), ('off_shoulder', 'Off Shoulder'), ('one_shoulder', 'One Shoulder'), ('henley', 'Henley')], max_length=32)),
                ('strap_type', models.CharField(choices=[('none', 'None'), ('strapless', 'Strapless'), ('spaghetti', 'Spaghetti'), ('thin', 'Thin'), ('medium', 'Medium'), ('wide', 'Wide'), ('halter', 'Halter'), ('one_shoulder', 'One Shoulder')], max_length=32)),
                ('silhouette', models.CharField(choices=[('straight', 'Straight'), ('a_line', 'A-Line'), ('bodycon', 'Bodycon'), ('fit_and_flare', 'Fit and Flare'), ('empire', 'Empire'), ('shift', 'Shift'), ('sheath', 'Sheath'), ('wrap', 'Wrap'), ('slip', 'Slip'), ('ball_gown', 'Ball Gown'), ('mermaid', 'Mermaid')], max_length=32)),
                ('dress_length', models.CharField(choices=[('mini', 'Mini'), ('above_knee', 'Above Knee'), ('knee', 'Knee'), ('midi', 'Midi'), ('maxi', 'Maxi'), ('floor', 'Floor')], max_length=32)),
                ('back_style', models.CharField(choices=[('closed', 'Closed'), ('open_back', 'Open Back'), ('low_back', 'Low Back'), ('cross_back', 'Cross Back'), ('racerback', 'Racerback'), ('keyhole', 'Keyhole'), ('lace_up', 'Lace Up')], max_length=32)),
                ('closure_type', models.CharField(choices=[('none', 'None'), ('pullover', 'Pullover'), ('buttons', 'Buttons'), ('zipper', 'Zipper'), ('half_zip', 'Half Zip'), ('quarter_zip', 'Quarter Zip'), ('snap', 'Snap'), ('hook_and_eye', 'Hook and Eye'), ('tie', 'Tie')], max_length=32)),
                ('fit', models.CharField(choices=[('skinny', 'Skinny'), ('slim', 'Slim'), ('fitted', 'Fitted'), ('regular', 'Regular'), ('relaxed', 'Relaxed'), ('oversized', 'Oversized'), ('boxy', 'Boxy')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'dress attributes',
            },
        ),
        migrations.CreateModel(
            name='FootwearAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shoe_height', models.CharField(choices=[('low', 'Low'), ('ankle', 'Ankle'), ('mid', 'Mid'), ('high', 'High'), ('knee', 'Knee'), ('over_knee', 'Over Knee')], max_length=32)),
                ('toe_shape', models.CharField(choices=[('round', 'Round'), ('almond', 'Almond'), ('square', 'Square'), ('pointed', 'Pointed'), ('open', 'Open'), ('wide', 'Wide')], max_length=32)),
                ('heel_type', models.CharField(choices=[('none', 'None'), ('flat', 'Flat'), ('block', 'Block'), ('stiletto', 'Stiletto'), ('kitten', 'Kitten'), ('wedge', 'Wedge'), ('platform', 'Platform'), ('cone', 'Cone')], max_length=32)),
                ('heel_height', models.CharField(choices=[('none', 'None'), ('flat', 'Flat'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=32)),
                ('shoe_closure', models.CharField(choices=[('none', 'None'), ('slip_on', 'Slip On'), ('laces', 'Laces'), ('zipper', 'Zipper'), ('buckle', 'Buckle'), ('velcro', 'Velcro'), ('strap', 'Strap'), ('elastic', 'Elastic')], max_length=32)),
                ('sole_type', models.CharField(choices=[('flat', 'Flat'), ('rubber', 'Rubber'), ('foam', 'Foam'), ('leather', 'Leather'), ('lug', 'Lug'), ('platform', 'Platform'), ('chunky', 'Chunky'), ('crepe', 'Crepe')], max_length=32)),
                ('shoe_profile', models.CharField(choices=[('minimal', 'Minimal'), ('standard', 'Standard'), ('chunky', 'Chunky'), ('sleek', 'Sleek'), ('athletic', 'Athletic'), ('rugged', 'Rugged')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'footwear attributes',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('cotton', 'Cotton'), ('organic_cotton', 'Organic Cotton'), ('denim', 'Denim'), ('linen', 'Linen'), ('wool', 'Wool'), ('merino_wool', 'Merino Wool'), ('cashmere', 'Cashmere'), ('silk', 'Silk'), ('satin', 'Satin'), ('velvet', 'Velvet'), ('corduroy', 'Corduroy'), ('leather', 'Leather'), ('faux_leather', 'Faux Leather'), ('suede', 'Suede'), ('faux_suede', 'Faux Suede'), ('polyester', 'Polyester'), ('nylon', 'Nylon'), ('acrylic', 'Acrylic'), ('spandex', 'Spandex'), ('elastane', 'Elastane'), ('rayon', 'Rayon'), ('viscose', 'Viscose'), ('modal', 'Modal'), ('fleece', 'Fleece'), ('jersey', 'Jersey'), ('canvas', 'Canvas'), ('mesh', 'Mesh'), ('lace', 'Lace'), ('chiffon', 'Chiffon'), ('tweed', 'Tweed'), ('rubber', 'Rubber'), ('synthetic', 'Synthetic'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnePieceAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleeve_length', models.CharField(choices=[('none', 'None'), ('sleeveless', 'Sleeveless'), ('cap', 'Cap'), ('short', 'Short'), ('elbow', 'Elbow'), ('three_quarter', 'Three Quarter'), ('long', 'Long'), ('extra_long', 'Extra Long')], max_length=32)),
                ('sleeve_type', models.CharField(choices=[('none', 'None'), ('regular', 'Regular'), ('raglan', 'Raglan'), ('set_in', 'Set In'), ('drop_shoulder', 'Drop Shoulder'), ('puff', 'Puff'), ('bell', 'Bell'), ('bishop', 'Bishop'), ('batwing', 'Batwing'), ('flutter', 'Flutter'), ('rolled', 'Rolled')], max_length=32)),
                ('neckline', models.CharField(choices=[('none', 'None'), ('crew', 'Crew'), ('round', 'Round'), ('v_neck', 'V-Neck'), ('deep_v', 'Deep V'), ('square', 'Square'), ('scoop', 'Scoop'), ('boat', 'Boat'), ('halter', 'Halter'), ('sweetheart', 'Sweetheart'), ('turtleneck', 'Turtleneck'), ('mock_neck', 'Mock Neck'), ('off_shoulder', 'Off Shoulder'), ('one_shoulder', 'One Shoulder'), ('henley', 'Henley')], max_length=32)),
                ('collar_type', models.CharField(choices=[('none', 'None'), ('shirt', 'Shirt'), ('spread', 'Spread'), ('point', 'Point'), ('button_down', 'Button Down'), ('mandarin', 'Mandarin'), ('polo', 'Polo'), ('camp', 'Camp'), ('peter_pan', 'Peter Pan'), ('shawl', 'Shawl'), ('notched', 'Notched'), ('stand', 'Stand')], max_length=32)),
                ('leg_shape', models.CharField(choices=[('none', 'None'), ('skinny', 'Skinny'), ('slim', 'Slim'), ('straight', 'Straight'), ('tapered', 'Tapered'), ('wide', 'Wide'), ('flare', 'Flare'), ('bootcut', 'Bootcut'), ('baggy', 'Baggy'), ('carrot', 'Carrot')], max_length=32)),
                ('length', models.CharField(choices=[('micro', 'Micro'), ('short', 'Short'), ('knee', 'Knee'), ('below_knee', 'Below Knee'), ('cropped', 'Cropped'), ('ankle', 'Ankle'), ('full', 'Full'), ('floor', 'Floor')], max_length=32)),
                ('waist_style', models.CharField(choices=[('none', 'None'), ('natural', 'Natural'), ('high', 'High'), ('low', 'Low'), ('elastic', 'Elastic'), ('drawstring', 'Drawstring'), ('belted', 'Belted'), ('fitted', 'Fitted')], max_length=32)),
                ('closure_type', models.CharField(choices=[('none', 'None'), ('pullover', 'Pullover'), ('buttons', 'Buttons'), ('zipper', 'Zipper'), ('half_zip', 'Half Zip'), ('quarter_zip', 'Quarter Zip'), ('snap', 'Snap'), ('hook_and_eye', 'Hook and Eye'), ('tie', 'Tie')], max_length=32)),
                ('fit', models.CharField(choices=[('skinny', 'Skinny'), ('slim', 'Slim'), ('fitted', 'Fitted'), ('regular', 'Regular'), ('relaxed', 'Relaxed'), ('oversized', 'Oversized'), ('boxy', 'Boxy')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'one piece attributes',
            },
        ),
        migrations.CreateModel(
            name='OuterwearAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleeve_length', models.CharField(choices=[('none', 'None'), ('sleeveless', 'Sleeveless'), ('cap', 'Cap'), ('short', 'Short'), ('elbow', 'Elbow'), ('three_quarter', 'Three Quarter'), ('long', 'Long'), ('extra_long', 'Extra Long')], max_length=32)),
                ('collar_type', models.CharField(choices=[('none', 'None'), ('shirt', 'Shirt'), ('spread', 'Spread'), ('point', 'Point'), ('button_down', 'Button Down'), ('mandarin', 'Mandarin'), ('polo', 'Polo'), ('camp', 'Camp'), ('peter_pan', 'Peter Pan'), ('shawl', 'Shawl'), ('notched', 'Notched'), ('stand', 'Stand')], max_length=32)),
                ('lapel_type', models.CharField(choices=[('none', 'None'), ('notch', 'Notch'), ('peak', 'Peak'), ('shawl', 'Shawl')], max_length=32)),
                ('closure_type', models.CharField(choices=[('none', 'None'), ('pullover', 'Pullover'), ('buttons', 'Buttons'), ('zipper', 'Zipper'), ('half_zip', 'Half Zip'), ('quarter_zip', 'Quarter Zip'), ('snap', 'Snap'), ('hook_and_eye', 'Hook and Eye'), ('tie', 'Tie')], max_length=32)),
                ('hood_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed'), ('detachable', 'Detachable'), ('oversized', 'Oversized'), ('drawstring', 'Drawstring')], max_length=32)),
                ('jacket_length', models.CharField(choices=[('cropped', 'Cropped'), ('waist', 'Waist'), ('hip', 'Hip'), ('mid_thigh', 'Mid Thigh'), ('knee', 'Knee'), ('below_knee', 'Below Knee'), ('full_length', 'Full Length')], max_length=32)),
                ('fit', models.CharField(choices=[('skinny', 'Skinny'), ('slim', 'Slim'), ('fitted', 'Fitted'), ('regular', 'Regular'), ('relaxed', 'Relaxed'), ('oversized', 'Oversized'), ('boxy', 'Boxy')], max_length=32)),
                ('insulation', models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('padded', 'Padded'), ('down', 'Down'), ('fleece_lined', 'Fleece Lined')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'outerwear attributes',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('none', 'None'), ('solid', 'Solid'), ('striped', 'Striped'), ('checked', 'Checked'), ('plaid', 'Plaid'), ('gingham', 'Gingham'), ('polka_dot', 'Polka Dot'), ('floral', 'Floral'), ('animal_print', 'Animal Print'), ('camouflage', 'Camouflage'), ('geometric', 'Geometric'), ('abstract', 'Abstract'), ('paisley', 'Paisley'), ('tie_dye', 'Tie Dye'), ('gradient', 'Gradient'), ('ombre', 'Ombre'), ('color_block', 'Color Block'), ('graphic', 'Graphic'), ('logo', 'Logo'), ('text', 'Text'), ('other', 'Other')], max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PocketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('side', 'Side'), ('slash', 'Slash'), ('patch', 'Patch'), ('chest', 'Chest'), ('cargo', 'Cargo'), ('welt', 'Welt'), ('zippered', 'Zippered'), ('kangaroo', 'Kangaroo'), ('back', 'Back'), ('coin', 'Coin'), ('hidden', 'Hidden'), ('flap', 'Flap')], max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('minimalist', 'Minimalist'), ('classic', 'Classic'), ('casual', 'Casual'), ('smart_casual', 'Smart Casual'), ('business_casual', 'Business Casual'), ('formal', 'Formal'), ('preppy', 'Preppy'), ('old_money', 'Old Money'), ('quiet_luxury', 'Quiet Luxury'), ('streetwear', 'Streetwear'), ('urban', 'Urban'), ('skater', 'Skater'), ('sporty', 'Sporty'), ('athleisure', 'Athleisure'), ('workwear', 'Workwear'), ('utility', 'Utility'), ('military', 'Military'), ('outdoorsy', 'Outdoorsy'), ('gorpcore', 'Gorpcore'), ('techwear', 'Techwear'), ('vintage', 'Vintage'), ('retro', 'Retro'), ('y2k', 'Y2K'), ('bohemian', 'Bohemian'), ('romantic', 'Romantic'), ('western', 'Western'), ('grunge', 'Grunge'), ('punk', 'Punk'), ('gothic', 'Gothic'), ('edgy', 'Edgy'), ('avant_garde', 'Avant Garde')], max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TopAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleeve_length', models.CharField(choices=[('none', 'None'), ('sleeveless', 'Sleeveless'), ('cap', 'Cap'), ('short', 'Short'), ('elbow', 'Elbow'), ('three_quarter', 'Three Quarter'), ('long', 'Long'), ('extra_long', 'Extra Long')], max_length=32)),
                ('sleeve_type', models.CharField(choices=[('none', 'None'), ('regular', 'Regular'), ('raglan', 'Raglan'), ('set_in', 'Set In'), ('drop_shoulder', 'Drop Shoulder'), ('puff', 'Puff'), ('bell', 'Bell'), ('bishop', 'Bishop'), ('batwing', 'Batwing'), ('flutter', 'Flutter'), ('rolled', 'Rolled')], max_length=32)),
                ('neckline', models.CharField(choices=[('none', 'None'), ('crew', 'Crew'), ('round', 'Round'), ('v_neck', 'V-Neck'), ('deep_v', 'Deep V'), ('square', 'Square'), ('scoop', 'Scoop'), ('boat', 'Boat'), ('halter', 'Halter'), ('sweetheart', 'Sweetheart'), ('turtleneck', 'Turtleneck'), ('mock_neck', 'Mock Neck'), ('off_shoulder', 'Off Shoulder'), ('one_shoulder', 'One Shoulder'), ('henley', 'Henley')], max_length=32)),
                ('collar_type', models.CharField(choices=[('none', 'None'), ('shirt', 'Shirt'), ('spread', 'Spread'), ('point', 'Point'), ('button_down', 'Button Down'), ('mandarin', 'Mandarin'), ('polo', 'Polo'), ('camp', 'Camp'), ('peter_pan', 'Peter Pan'), ('shawl', 'Shawl'), ('notched', 'Notched'), ('stand', 'Stand')], max_length=32)),
                ('shoulder_style', models.CharField(choices=[('none', 'None'), ('regular', 'Regular'), ('drop_shoulder', 'Drop Shoulder'), ('raglan', 'Raglan'), ('structured', 'Structured'), ('padded', 'Padded'), ('off_shoulder', 'Off Shoulder'), ('one_shoulder', 'One Shoulder')], max_length=32)),
                ('hem_style', models.CharField(choices=[('none', 'None'), ('straight', 'Straight'), ('curved', 'Curved'), ('rounded', 'Rounded'), ('asymmetric', 'Asymmetric'), ('cropped', 'Cropped'), ('ribbed', 'Ribbed'), ('raw', 'Raw'), ('split', 'Split')], max_length=32)),
                ('closure_type', models.CharField(choices=[('none', 'None'), ('pullover', 'Pullover'), ('buttons', 'Buttons'), ('zipper', 'Zipper'), ('half_zip', 'Half Zip'), ('quarter_zip', 'Quarter Zip'), ('snap', 'Snap'), ('hook_and_eye', 'Hook and Eye'), ('tie', 'Tie')], max_length=32)),
                ('hood_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed'), ('detachable', 'Detachable'), ('oversized', 'Oversized'), ('drawstring', 'Drawstring')], max_length=32)),
                ('fit', models.CharField(choices=[('skinny', 'Skinny'), ('slim', 'Slim'), ('fitted', 'Fitted'), ('regular', 'Regular'), ('relaxed', 'Relaxed'), ('oversized', 'Oversized'), ('boxy', 'Boxy')], max_length=32)),
                ('length', models.CharField(choices=[('cropped', 'Cropped'), ('waist', 'Waist'), ('hip', 'Hip'), ('longline', 'Longline'), ('oversized_long', 'Oversized Long')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'top attributes',
            },
        ),
        migrations.CreateModel(
            name='VisualAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dominant_color_hex', models.CharField(blank=True, default='', max_length=7)),
                ('brightness', models.CharField(choices=[('very_dark', 'Very Dark'), ('dark', 'Dark'), ('medium', 'Medium'), ('light', 'Light'), ('very_light', 'Very Light')], max_length=32)),
                ('saturation', models.CharField(choices=[('desaturated', 'Desaturated'), ('muted', 'Muted'), ('medium', 'Medium'), ('vibrant', 'Vibrant'), ('highly_vibrant', 'Highly Vibrant')], max_length=32)),
                ('visual_complexity', models.CharField(choices=[('very_simple', 'Very Simple'), ('simple', 'Simple'), ('moderate', 'Moderate'), ('busy', 'Busy'), ('very_busy', 'Very Busy')], max_length=32)),
                ('statement_level', models.CharField(choices=[('basic', 'Basic'), ('subtle', 'Subtle'), ('moderate', 'Moderate'), ('statement', 'Statement'), ('bold', 'Bold')], max_length=32)),
                ('structure', models.CharField(choices=[('soft', 'Soft'), ('semi_structured', 'Semi Structured'), ('structured', 'Structured'), ('rigid', 'Rigid')], max_length=32)),
                ('surface_finish', models.CharField(choices=[('matte', 'Matte'), ('semi_matte', 'Semi Matte'), ('semi_gloss', 'Semi Gloss'), ('glossy', 'Glossy'), ('metallic', 'Metallic'), ('sparkly', 'Sparkly')], max_length=32)),
                ('transparency', models.CharField(choices=[('opaque', 'Opaque'), ('slightly_sheer', 'Slightly Sheer'), ('sheer', 'Sheer'), ('transparent', 'Transparent')], max_length=32)),
                ('symmetry', models.CharField(choices=[('symmetric', 'Symmetric'), ('mostly_symmetric', 'Mostly Symmetric'), ('asymmetric', 'Asymmetric')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'visual attributes',
            },
        ),
        migrations.CreateModel(
            name='ClothingSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('one_piece', 'One Piece')], max_length=32)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'clothing subcategories',
                'ordering': ['type_name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('type_name', 'name'), name='wardrobe_subcategory_type_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('one_piece', 'One Piece')], max_length=32)),
                ('bottom_attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_type', to='wardrobe.bottomattributes')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clothing_types', to='wardrobe.clothingsubcategory')),
                ('dress_attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_type', to='wardrobe.dressattributes')),
                ('footwear_attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_type', to='wardrobe.footwearattributes')),
                ('one_piece_attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_type', to='wardrobe.onepieceattributes')),
                ('outerwear_attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_type', to='wardrobe.outerwearattributes')),
                ('top_attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_type', to='wardrobe.topattributes')),
            ],
            options={
                'verbose_name': 'clothing type',
            },
        ),
        migrations.CreateModel(
            name='ClothingColorGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent')], max_length=16)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.clothingcolorgroup')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_items', to='wardrobe.color')),
            ],
            options={
                'verbose_name': 'clothing color group item',
                'ordering': ['role', 'color__name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingDetailGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.clothingdetailgroup')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_items', to='wardrobe.detail')),
            ],
            options={
                'verbose_name': 'clothing detail group item',
                'ordering': ['detail__name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingMaterialGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.clothingmaterialgroup')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_items', to='wardrobe.material')),
            ],
            options={
                'verbose_name': 'clothing material group item',
                'ordering': ['material__name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingPatternGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scale', models.CharField(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('mixed', 'Mixed')], max_length=16)),
                ('density', models.CharField(choices=[('none', 'None'), ('sparse', 'Sparse'), ('medium', 'Medium'), ('dense', 'Dense')], max_length=16)),
                ('orientation', models.CharField(choices=[('none', 'None'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('diagonal', 'Diagonal'), ('mixed', 'Mixed')], max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.clothingpatterngroup')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_items', to='wardrobe.pattern')),
            ],
            options={
                'verbose_name': 'clothing pattern group item',
                'ordering': ['pattern__name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingPocketGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.clothingpocketgroup')),
                ('pocket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_items', to='wardrobe.pockettype')),
            ],
            options={
                'verbose_name': 'clothing pocket group item',
                'ordering': ['pocket_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingStyleGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.clothingstylegroup')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_items', to='wardrobe.style')),
            ],
            options={
                'verbose_name': 'clothing style group item',
                'ordering': ['-confidence', 'style__name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_item', to='wardrobe.clothinganalysis')),
                ('color_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='wardrobe.clothingcolorgroup')),
                ('detail_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='wardrobe.clothingdetailgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
                ('material_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='wardrobe.clothingmaterialgroup')),
                ('pattern_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='wardrobe.clothingpatterngroup')),
                ('pocket_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='wardrobe.clothingpocketgroup')),
                ('style_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='wardrobe.clothingstylegroup')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clothing_items', to='wardrobe.clothingtype')),
                ('visual_attributes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_item', to='wardrobe.visualattributes')),
            ],
            options={
                'verbose_name': 'clothing item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clothingtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bottom_attributes__isnull', True), ('dress_attributes__isnull', True), ('footwear_attributes__isnull', True), ('one_piece_attributes__isnull', True), ('outerwear_attributes__isnull', True), ('top_attributes__isnull', False)), models.Q(('bottom_attributes__isnull', False), ('dress_attributes__isnull', True), ('footwear_attributes__isnull', True), ('one_piece_attributes__isnull', True), ('outerwear_attributes__isnull', True), ('top_attributes__isnull', True)), models.Q(('bottom_attributes__isnull', True), ('dress_attributes__isnull', False), ('footwear_attributes__isnull', True), ('one_piece_attributes__isnull', True), ('outerwear_attributes__isnull', True), ('top_attributes__isnull', True)), models.Q(('bottom_attributes__isnull', True), ('dress_attributes__isnull', True), ('footwear_attributes__isnull', True), ('one_piece_attributes__isnull', True), ('outerwear_attributes__isnull', False), ('top_attributes__isnull', True)), models.Q(('bottom_attributes__isnull', True), ('dress_attributes__isnull', True), ('footwear_attributes__isnull', False), ('one_piece_attributes__isnull', True), ('outerwear_attributes__isnull', True), ('top_attributes__isnull', True)), models.Q(('bottom_attributes__isnull', True), ('dress_attributes__isnull', True), ('footwear_attributes__isnull', True), ('one_piece_attributes__isnull', False), ('outerwear_attributes__isnull', True), ('top_attributes__isnull', True)), _connector='OR'), name='wardrobe_clothingtype_exactly_one_attribute'),
        ),
    ]
